### ISSUE TITLE
Can't build on raspberry pi 3

### ISSUE THREAD

**Issue by fubsteru** [herber/cargo#10]
Build fails on raspberry pi 3 with : 
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

I've used $ yarn build:all from the README.md
see below npm-debug.log 

pi@raspberrypi:~/Downloads/cargo-0.0.1-beta $ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   '--all' ]
2 info using npm@2.15.11
3 info using node@v8.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild cargo@0.0.1
6 info build cargo@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info cargo@0.0.1 Failed to exec build script
9 verbose stack Error: cargo@0.0.1 build: `build . "--all"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:126:13)
9 verbose stack     at EventEmitter.emit (events.js:214:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:126:13)
9 verbose stack     at ChildProcess.emit (events.js:214:7)
9 verbose stack     at maybeClose (internal/child_process.js:925:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
10 verbose pkgid cargo@0.0.1
11 verbose cwd /home/pi/Downloads/cargo-0.0.1-beta
12 error Linux 4.9.35-v7+
13 error argv "/usr/bin/node" "/usr/local/bin/npm" "run" "build" "--" "--all"
14 error node v8.9.1
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error cargo@0.0.1 build: `build . "--all"`
17 error Exit status 1
18 error Failed at the cargo@0.0.1 build script 'build . "--all"'.
18 error This is most likely a problem with the cargo package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     build . "--all"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs cargo
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls cargo
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Not sure what is worng.

Thanks,

**Comment by herber** [comment]
Since raspberrypis are based on arm I don't think they are able to build x64 or ia32 binaries.

You could try running `yarn build --linux --armv7l`, this will create a binary for arm based linux machines, like your raspberry pi.

**Comment by herber** [comment]
Closing now due to inactivity - I will reopen the issue if necessary.
