### ISSUE TITLE
Hide placeholder on startpage when input field is clicked

### ISSUE THREAD

**Issue by bcye** [herber/cargo#14]
It would be better to hide the destination placeholder, if the field was clicked. ATM the typing cursor is blinking over the text field (see screenshot)
![Screen_Shot_2018-02-19_at_23.44.07.png](https://s10.postimg.org/cu0jirdl5/Screen_Shot_2018-02-19_at_23.44.07.png)(https://postimg.org/image/x1dzb2b2d/)

**Comment by herber** [comment]
Sounds like an interesting idea, however I am not sure about the UX. This will probably become an optional thing, I'm going to add it, when cargo has settings.

[Demo](https://jsfiddle.net/herber/5pszgs4o/embedded/result/)
