### ISSUE TITLE
Wrong result when typing a '#' into the searchbar

### ISSUE THREAD

**Issue by NimmLor** [herber/cargo#25]
I've noticed a bug in cargo. If you type for instance "c# remove last element of list", it will come up with the same results as if I just searched "c". The URL that gets opened is "https://duckduckgo.com/?q=c# remove last element of list".

This behavior might be caused by the '#' that is needs to be escaped.

**Comment by herber** [comment]
Thanks for reporting, this will be fixed in version 1.0. But if you need it now, feel free to create a pull request.

Closing for now.
