### ISSUE TITLE
Feature request: Bookmarks?

### ISSUE THREAD

**Issue by BraydenTW** [herber/cargo#33]
Hi!

Cargo Browser looks awesome! I think the one thing that’s keeping me from migrating to Cargo is no bookmark feature.

Would this be something added in the future? I feel that it is very important and shouldn’t be left out.

**Comment by herber** [comment]
Hey, there.

I 100% agree with you. Bookmarks are pretty important. I just haven't had the time to implement them yet - because I want to implement them well. I'm open to contributions if you want to implement a bookmarking feature.
